server:
  port: 5101

spring:
  application:
    name: redis-sample

  datasource:
    url: jdbc:mysql://localhost:3306/comma_admin?useSSL=false&autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  jpa:
    show-sql: true
    open-in-view: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: localhost
    port: 6379
    database: 0


logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

